services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '3307:3306'
    volumes:
      - ./timeless_song.sql:/docker-entrypoint-initdb.d/timeless_song.sql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:1.0.0
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 020521
      DB_NAME: timeless_song_spotify