from sqlalchemy import Column, Integer, String, BigInteger,Float
from database.__init__ import Base

class top_80(Base):
    __tablename__ = 'top_80s'
    song = Column(String(100))
    artist= Column(String(100))
    Hot100_Rank = Column(Integer)
    uri = Column(String(50))
    danceability = Column(Float)
    energy = Column(Float)
    key = Column(Integer)
    loudness = Column(Float)
    mode = Column(Integer)
    speechiness = Column(Float)
    acousticness = Column(Float)
    instrumentalness = Column(Float)
    liveness = Column(Float)
    valence = Column(Float)
    tempo = Column(Float)
    duration_ms = Column(Integer)
    time_signature = Column(Integer)
    chorus_hit = Column(Float)
    sections = Column(Integer)
    country = Column(String(50))
    song_id = Column(String(50), primary_key=True)
    genre = Column(String(50))
    streams = Column(Float)
print ("80s model created successfully.")

class top_90(Base):
    __tablename__ = 'top_90s'
    song = Column(String)
    artist= Column(String)
    Hot100_Rank = Column(Integer)
    uri = Column(String(50))
    danceability = Column(Float)
    energy = Column(Float)
    key = Column(Integer)
    loudness = Column(Float)
    mode = Column(Integer)
    speechiness = Column(Float)
    acousticness = Column(Float)
    instrumentalness = Column(Float)
    liveness = Column(Float)
    valence = Column(Float)
    tempo = Column(Float)
    duration_ms = Column(Integer)
    time_signature = Column(Integer)
    chorus_hit = Column(Float)
    sections = Column(Integer)
    country = Column(String(50))
    song_id = Column(String(50), primary_key=True)
    genre = Column(String(50))
    streams = Column(Float)
print ("90s model created successfully.")